#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.\n"; exit 2; }
git lfs post-checkout "$@"

# Only update submodules when checkout is used to change commit, not just checkout a file.
if [ $3 -eq 1 ]
then
  git submodule update --init --recursive
fi
